name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      
    - name: Get Ginkgo
      run: go get github.com/onsi/ginkgo/ginkgo
      
    - name: Get Gomega
      run: go get github.com/onsi/gomega/...
      
    - name: Get Code Coverage converter
      run: go get -u github.com/jandelgado/gcov2lcov

    - name: Test
      run:  ginkgo -r -race -cover --afterSuiteHook="gcov2lcov -infile=go-nmea.coverprofile -outfile=lcov.info"
      
